config/routes.rb
CareerCenterApp::Application.routes.draw do
  resources :users

  resources :messages

  get "conferences/select_con" => "conferences#select_con"
  get "conferences/set_session" => "conferences#set_session"
  resources :conferences

  resources :tables

  get'employers/conf/' => "employers#index"
  get  "employers/favorites" => "employers#index", :favorites => true
  get  "employers/:id/favorite" => "employers#favorite", :as => "favorite"
  get  "employers/:id/defavorite" => "employers#defavorite", :as => "defavorite"
  get  "employers/import_form" => "employers#import_form"
  post "employers/import_from_csv" => "employers#import_from_csv"
  get  "employers/maps/:conferences" => "employers#maps"
  get  "employers/landing" => "employers#landing", :as => "landing"
  get  "employers/about_us" => "employers#about_us", :as => "about_us"

  get  "employers/map" => "employers#map"
  post "employers/map_upload" => "employers#map_upload"

  get  "employers/directions" => "employers#directions"

  resources :employers

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resource :sessions, only: [:new, :create, :destroy] , :controller => 'sessions'

   root 'employers#landing'

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user, foreign_key: "to"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    
    @Ctime = Time.now


  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:to, :from, :from_role, :read, :content, :expiration)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

 <div class="field">
    <%= f.label :expiration %><br>
    <%= f.datetime_select :expiration, ampm: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table style="font-size:20px;">
  <thead>
    <tr>
      <% if admin? %>
        <th>Expires</th>
        <th>Content</th>
      <% end %>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
         <td><%= message.expiration.strftime("%m/%d/%Y %I:%M%p") %></td>
        <td style="font-size:20px; padding:10px"><%= message.content %></td>
        <% if admin? %>
          <td><%= link_to 'Show', message, {class: 'btn btn-info btn-sm'} %></td>
          <td><%= link_to 'Edit', edit_message_path(message), {class: 'btn btn-info btn-sm'} %></td>
          <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
        <% end %>
      </tr>
      <% end if @messages.count > 0 %>
  </tbody>
</table>

<br>
<% if admin? %>
  <%= link_to 'New Message', new_message_path, {class: 'btn btn-success'} %>
<% end %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>
 <% if @message.expiration  %>
    <p>
      <strong> Expired:</strong> 
      <%= (Time.now >= @message.expiration + 4.hour) %> 
    </p>

    <p>
      <strong> Expires:</strong>
      <%= @message.expiration %>
    </p>
  <% end %>
<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>