config/routes.rb
CareerCenterApp::Application.routes.draw do
  resources :users

  resources :messages

  get "conferences/select_con" => "conferences#select_con"
  get "conferences/set_session" => "conferences#set_session"
  resources :conferences

  resources :tables

  get'employers/conf/' => "employers#index"
  get  "employers/favorites" => "employers#index", :favorites => true
  get  "employers/:id/favorite" => "employers#favorite", :as => "favorite"
  get  "employers/:id/defavorite" => "employers#defavorite", :as => "defavorite"
  get  "employers/import_form" => "employers#import_form"
  post "employers/import_from_csv" => "employers#import_from_csv"
  get  "employers/maps/:conferences" => "employers#maps"
  get  "employers/landing" => "employers#landing", :as => "landing"
  get  "employers/about_us" => "employers#about_us", :as => "about_us"

  get  "employers/map" => "employers#map"
  post "employers/map_upload" => "employers#map_upload"

  get  "employers/directions" => "employers#directions"

  resources :employers

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resource :sessions, only: [:new, :create, :destroy] , :controller => 'sessions'

   root 'employers#landing'

end

app/models/conference.rb
class Conference < ActiveRecord::Base
	has_many :tables
	has_many :employers
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]

  # Get /conferences/pick or /home or some url 
  def select_con
    @conferences = Conference.all
  end

  def set_session
    session[:current_con] = params[:con_id] if params[:con_id]
    redirect_to employers_path
    #redirect to the emplyoers controller and pass a param that tells ruby we need to filter 
    #redirect_to :controller => "employers", :action => 'index', :fair => session[:current_con] 
  end

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render action: 'show', status: :created, location: @conference }
      else
        format.html { render action: 'new' }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end

  def each
    @conference = Conference.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :location, :description, :last_edit) if params[:conference]
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :last_edit %><br>
    <%= f.text_field :last_edit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<h1>Listing fairs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Description</th>
      <th>Last edit</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= conference.name %></td>
        <td><%= conference.location %></td>
        <td><%= conference.description %></td>
        <td><%= conference.last_edit %></td>
        <td><%= link_to 'Show', conference %></td>
        <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fair', new_conference_path %>

app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/select_con.html.erb
<h1>All Job Fairs</h1>
<!-- This is going to generate all the buttons for each fair, we click on one, its going to set the fair selected  
to the users choice , then load that fair -->
<% @conferences.each do |conference| %>
  <div>
 	<span class="btn btn-info btn-lg">
 		<%= link_to conference.name, action: :set_session, con_id: conference.id %>
  	</span>
  </div>
<br>

<% end %>

app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conference.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @conference.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @conference.description %>
</p>

<p>
  <strong>Last edit:</strong>
  <%= @conference.last_edit %>
</p>

<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>