config/routes.rb
CareerCenterApp::Application.routes.draw do
  resources :users

  resources :messages

  get "conferences/select_con" => "conferences#select_con"
  get "conferences/set_session" => "conferences#set_session"
  resources :conferences

  resources :tables

  get'employers/conf/' => "employers#index"
  get  "employers/favorites" => "employers#index", :favorites => true
  get  "employers/:id/favorite" => "employers#favorite", :as => "favorite"
  get  "employers/:id/defavorite" => "employers#defavorite", :as => "defavorite"
  get  "employers/import_form" => "employers#import_form"
  post "employers/import_from_csv" => "employers#import_from_csv"
  get  "employers/maps/:conferences" => "employers#maps"
  get  "employers/landing" => "employers#landing", :as => "landing"
  get  "employers/about_us" => "employers#about_us", :as => "about_us"

  get  "employers/map" => "employers#map"
  post "employers/map_upload" => "employers#map_upload"

  get  "employers/directions" => "employers#directions"

  resources :employers

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resource :sessions, only: [:new, :create, :destroy] , :controller => 'sessions'

   root 'employers#landing'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  belongs_to :conference
  has_one :table
  before_save :clean_logo

  default_scope {order('name')}
  scope :by_conference, ->(con_id) {where(conference_id: con_id) if con_id}

  private
    def clean_logo
      self.logo = self.logo.original_filename if self.logo.class != String && !self.logo.nil?
    end
end

app/controllers/employers_controller.rb
require 'csv'

class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy, :favorite, :defavorite]
  before_action :grant_access, only: [:edit, :update, :destroy, :create, :import_form, :import_from_csv]
  before_action :logged_in, only: [:favorite]

  def landing
    redirect_to conferences_select_con_path if current_user
  end

  def about_us
  end

  def favorite
    current_user.add_favorite(@employer.id)
    if current_user.save!
      flash[:success] = "Added #{@employer.name} from favorites."
      redirect_to :back
    else
      flash[:error] = "Something went wrong!"
      redirect_to :back
    end
  end

  def defavorite
    current_user.remove_favorite(@employer.id)
    if current_user.save!
      flash[:success] = "Removed #{@employer.name} from favorites."
      redirect_to :back
    else
      flash[:error] = "Something went wrong!"
      redirect_to :back
    end
  end

  def maps
    if params[:conference]== "set" || params[:conference]=="SET"
      @img_src="assets/maps/set/set.jpg"#define a string that is the path to that source
    elsif params[:conference]== "fest" || params[:conference]=="FEST"
      @img_src="path/to/fest_fair_map.jpg"
    else
      @img_src="path/to/default_map.jpg"
    end
  end

  def map
    #we redirect the user to select_con if no fair has been set
    unless current_con
      redirect_to :controller => "conferences", :action => 'select_con'
    end
  end

  def map_upload
    uploaded_io = params[:map]

    File.open(Rails.root.join('public', 'uploads', 'maps', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    current_con.update_attributes(map: uploaded_io.original_filename)

    flash[:notice] = "Map saved!"
    redirect_to :controller => "employers", :action => 'map'
  end

  # GET /employers
  # GET /employers.json
  def index
    if current_con
      @employers = Employer.includes(:conference).by_conference(current_con.id).find(current_user.favorites.map(&:to_i)) if params[:favorites] && current_user && !current_user.favorites.empty?
      @employers ||= Employer.includes(:conference).where("conference_id = ?", current_con.id).by_conference(current_con).all
      # comment
      @messages = Message.where("expiration > ?", Time.now - 4.hours)
    else
      redirect_to :controller => "conferences", :action => 'select_con'
    end
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    if current_con
      @employer = Employer.new
    else
      redirect_to :controller => "conferences", :action => 'select_con'
    end
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employer }
      else
        format.html { render action: 'new' }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    uploaded_io = employer_params[:logo]

    File.open(Rails.root.join('public', 'uploads', 'company_logos', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end unless employer_params[:logo].blank?

    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    User.where("'#{@employer.id}' = ANY (favorites)").each do |u|
      u.remove_favorite(@employer.id)
      u.save
    end


    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url }
      format.json { head :no_content }
    end
  end

  def import_form
    @conferences = Conference.all
  end

  def import_from_csv
    uploaded_io = params[:employers_csv]
    conference_id = params[:conference_id]

    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    CSV.foreach(Rails.root.join('public', 'uploads', uploaded_io.original_filename), :headers => true) do |row|
      unless row[1].nil? || row[1].empty?

        positions = Array.new
        positions << "Full Time"                 unless row[3].nil?  || row[3].empty?
        positions << "Part Time"                 unless row[4].nil?  || row[4].empty?
        positions << "Internship"                unless row[5].nil?  || row[5].empty?
        positions << "Co-Op"                     unless row[6].nil?  || row[6].empty?
        positions << "In SC"                     unless row[7].nil?  || row[7].empty?
        positions << "In Southeast"              unless row[8].nil?  || row[8].empty?
        positions << "Nationwide Positions"      unless row[9].nil?  || row[9].empty?
        positions << "Day After Fair Interviews" unless row[10].nil? || row[10].empty?

        Employer.create!({
          table_s: row[0],
          name: row[1],
          majors: row[2],
          description: row[11] || "",
          website: row[12] || "",
          location: row[13] || "",
          tips: row[14] || "",
          email: row[15] || "",
          conference_id: conference_id,
          positions: positions.join(',')
        })
      end
    end

    params[:employers_csv] = uploaded_io.original_filename
    flash[:sucess] = "The employers document, #{params[:employers_csv]} has been uploaded!"



    # if saved
    #   flash[:sucess] = "The employers document, #{params[:employers_csv]} has been uploaded!"
    # else
    #   flash[:error] = "There was a problem uploading your document."
    # end

    redirect_to employers_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.includes(:conference).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:name, :website, :description, :logo, :majors, :email, :positions, :tips, :created_at, :updated_at, :last_edit, :table_id, :conference_id, :location) if params[:employer]
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for(@employer, multipart: true) do |f| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% @employer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="control-group">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="control-group">
    <% unless @employer.logo.blank? %>
    <%= image_tag "/uploads/company_logos/#{@employer.logo}" , class: "logos" %>
    <% end %>
    <br/>
    <p>Choose a new file to add logo or replace current.</p>
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="control-group">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="control-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="control-group">
    <%= f.label :majors %><br>
    <%= f.text_area :majors %>
  </div>
  <div class="control-group">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="control-group">
    <%= f.label :positions %><br>
    <%= f.text_area :positions %>
  </div>
  <div class="control-group">
    <%= f.label :tips %><br>
    <%= f.text_area :tips %>
  </div>
  <div class="control-group">
    <%= f.label :table_s, "Table Number(s)" %><br>
    <%= f.number_field :table_s %>
  </div>
  <div class="control-group">
    <%= f.label :conference_id %><br>
    <%= f.collection_select :conference_id, Conference.order(:name),:id,:name, include_blank: false, :prompt => "Pick Conference" %>
  </div>
  <%= f.hidden_field :last_edit, :value => current_user.name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employers/about_us.html.erb
<div class="about-us">
  <h1>About Us</h1>
  <p>Career Center Companion was developed by students at the University of South Carolina</p>
  <h2>We are</h2>
  <ul>
    <li><a href="https://github.com/ballardaf">Andrew Ballard</a></li>
    <li><a href="https://github.com/andrewkazura">Andrew Kazura</a></li>
    <li><a href="https://github.com/jayposton">James Poston</a></li>
    <li><a href="https://github.com/finleye">Corey Finley</a></li>
  </ul>
</div>

app/views/employers/directions.html.erb
<h1><font size="15">Directions to <%= current_con.name%></font></a></h1>
<div>
	<iframe width="500" height="500" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=d&amp;source=s_d&amp;saddr=The+Horseshoe,+Sumter+Street,+Columbia,+SC&amp;daddr=Columbia+Metropolitan+Convention+Center,+1101+Lincoln+Street,+Columbia,+SC+29201&amp;hl=en&amp;geocode=FU_FBgId7Zgr-yGSOn7Z2ORq_iklRl7N1br4iDGSOn7Z2ORq_g%3BFdrBBgIdMnUr-ymtnGCjLrv4iDGEp34fmj4bVw&amp;aq=0&amp;oq=The+Horse&amp;sll=33.99842,-81.036319&amp;sspn=0.00378,0.004935&amp;t=h&amp;mra=ls&amp;ie=UTF8&amp;ll=33.999632,-81.034355&amp;spn=0.004394,0.008357&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=d&amp;source=embed&amp;saddr=The+Horseshoe,+Sumter+Street,+Columbia,+SC&amp;daddr=Columbia+Metropolitan+Convention+Center,+1101+Lincoln+Street,+Columbia,+SC+29201&amp;hl=en&amp;geocode=FU_FBgId7Zgr-yGSOn7Z2ORq_iklRl7N1br4iDGSOn7Z2ORq_g%3BFdrBBgIdMnUr-ymtnGCjLrv4iDGEp34fmj4bVw&amp;aq=0&amp;oq=The+Horse&amp;sll=33.99842,-81.036319&amp;sspn=0.00378,0.004935&amp;t=h&amp;mra=ls&amp;ie=UTF8&amp;ll=33.999632,-81.034355&amp;spn=0.004394,0.008357" style="color:#0000FF;text-align:left">View Larger Map</a></small>
</div>

app/views/employers/edit.html.erb
<h1>Editing employer</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/employers/import_form.html.erb
<%= form_tag("/employers/import_from_csv", multipart: true) do %>
  <%= label_tag('employers_csv', "Import:") %>
  <%= file_field_tag 'employers_csv' %>
  <br/>

  <%= label_tag('conference_id', "Destination Conference:") %>
  <br/>
  <select id='conference_id' name='conference_id'>
    <% @conferences.each do |con| %>
      <option value="<%= con.id %>"><%= con.name %></option>
    <% end %>
  </select>

  <%= submit_tag("Import") %>
<% end %>

app/views/employers/index.html.erb
<% @messages.each do |msg| %>
  <div class="alert alert-info"><button type="button" class="close" data-dismiss="alert">&times;</button><%= msg.content %></div> 
<% end %>

<h1>Employers</h1>
<table class="table table-striped">
  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td class="employers">
        <% if current_user && !current_user.favorites.nil? && current_user.favorites.include?(employer.id.to_s)   %>

          <a href="/employers/<%= employer.id %>/defavorite"><button type="button" class="btn fair-btn btn-warning btn-lg"><span class="glyphicon glyphicon-star"></span></button></a>
        <% else %>
          <a href="/employers/<%= employer.id %>/favorite"><button type="button" class="btn fair-btn btn-default btn-lg"><span class="glyphicon glyphicon-star-empty"></span></button></a>
        <% end %>
        </td>
        <td>
          <h3><%= link_to employer.name, employer %> <small><%= employer.location %></small></h3>
          <p class="hidden-lg">
            <% employer.majors.split(',').each do |major| %>
              <span class="label label-primary"><%= major.split(' ').map{|x| x[0..2]}.join('') %></span>
            <% end unless employer.majors.blank? %>
          </p>
          <p class="hidden-lg">
            <% employer.positions.split(',').each do |pos| %>
              <span class="label label-default"><%= pos %></span>
            <% end unless employer.positions.blank? %>

          </p>
          <%= link_to 'More Info', employer, {class: "btn btn-default hidden-lg"} %>
          <p class="visible-lg"><%= employer.description %></p>
        </td>
        <td class="visible-lg">
          <% employer.majors.split(',').each do |major| %>
            <span class="label label-primary"><%= major %></span>
          <% end unless employer.majors.blank? %>
        </td>
        <td class="visible-lg">
          <% employer.positions.split(',').each do |pos| %>
            <span class="label label-default"><%= pos %></span>
          <% end unless employer.positions.blank? %>
        </td>

        <% if admin? %>
          <td><%= link_to 'Show', employer, {class: "btn btn-default"} %></td>
          <td><%= link_to 'Edit', edit_employer_path(employer), {class: "btn btn-default"}%></td>
          <td><%= link_to 'Destroy', employer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% else %>
          <td class="visible-lg">
            <%= link_to 'More Info', employer, {class: "btn btn-default"} %>
          </td>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <p>
       *Southeast Refers to: TN, GA, LA, AL, FL, SC, AR, KY, MS
      </p>
    </tr>
  </tbody>
</table>
<br>

<% if admin? %>
<%= link_to 'New Employer', new_employer_path , {class: "btn btn-success"}%>
<%= link_to 'Import CSV', employers_import_form_path , {class: "btn btn-success"} %>
<% end %>
</div>

app/views/employers/landing.html.erb
<div class="landing">
  <div class="header">
    <h1>
      Career Center Companion
    </h1>
  </div>
  <div class="video">
    <iframe width="560" height="315" src="//www.youtube.com/embed/E44FhfeLEUU" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="detail">
    <h2>An easy to use job fair companion</h2>
    <p>The Career Center Companion is an easy to use application that simplifies the experience of going to a job fair. Rather than carrying around a packet of information flipping back and forth for information, use this app on your phone and find employer information at your fingertips.</p>
    <h3>Key features</h3>
    <p>See employer descriptions, and link to their site or where to find more infomation</p>
    <p>Favorite employers, to make sure you visit your top picks</p>
    <p>Quickly see the majors and work locaitons for each employer</p>
    <p>View the conference table map, and easily find employer locations within the fair</p>
    <p>Get important notifications from conference organizers about changes or external meetings</p>
  </div>
  <div>
    <h7><font size= "15">About Us</font></h7>
    <p>Corey Finely</p>
    <p>Andrew Ballard</p>
    <p>Andrew Kazura</p>
    <p>James Poston</p>
  </div>
</div>

app/views/employers/map.html.erb
<h1>Map - <%= current_con.name %> </h1>
<br>
<div id = "map_container">
<%= image_tag("/uploads/maps/#{current_con.map}", class: "maps") %>
</div>

<% if current_user && admin? %>
  <%= form_tag("/employers/map_upload", multipart: true) do %>
  <%= label_tag(:q, "Upload:") %>
  <%= file_field_tag 'map' %>
  <%= submit_tag("Upload") %>
  <% end %>
<% end %>

app/views/employers/new.html.erb
<h1>New employer</h1>

<%= render 'form' %>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.erb
<h1><%= @employer.name %> <small><%= @employer.location %></small></h1>

<div class="row row-fluid">
  <div class="col-lg-6">
    <p>
      <% @employer.majors.split(',').each do |major| %>
        <span class="label label-primary"><%= major %></span>
      <% end if @employer.majors %>
    </p>
    <p>
      <% @employer.positions.split(',').each do |pos| %>
        <span class="label label-default"><%= pos %></span>
      <% end if @employer.positions %>
    </p>
    <p><%= @employer.description %></p>
    <% if current_user && !current_user.favorites.nil? && current_user.favorites.include?(@employer.id.to_s) %>
      <a href="/employers/<%= @employer.id %>/defavorite"><button type="button" class="btn fair-btn btn-warning btn-lg"><span class="glyphicon glyphicon-star"></span> Favorite</button></a>
    <% else %>
      <a href="/employers/<%= @employer.id %>/favorite"><button type="button" class="btn fair-btn btn-default btn-lg"><span class="glyphicon glyphicon-star-empty"></span> Favorite</button></a>
    <% end %>
    <% if !@employer.website.nil? %>
    <a href="http://<%= @employer.website %>"><button type="button" class="btn fair-btn btn-primary btn-lg"><span class="glyphicon glyphicon-share-alt"></span> Website</button></a>
    <% end %> 
  </div>
  <div class="col-lg-6">
    <% unless @employer.logo.blank? %>
    <%= image_tag("/uploads/company_logos/#{@employer.logo}" , class: "logos")%>
    <% end %>
    <p>
      <strong>Tips:</strong>
      <%= @employer.tips %>
    </p>


    <p>
      <strong>Table:</strong>
      <%= @employer.table_s %>
    </p>

    <p>
      <strong>Conference:</strong>
      <%= @employer.conference.name if @employer.conference%>
    </p>

    <% if admin? %>
    <p>
      <strong>Last edit:</strong>
      <% if @employer.last_edit %>
        <%= @employer.last_edit %>
      <% else %>
        No User Data
      <% end %>
    </p>
    <% end %>
  </div>
</div>
<br/><br/>
<% if admin? %>
<%= link_to 'Edit', edit_employer_path(@employer), {class: "btn btn-default"}%>
<%= link_to 'Destroy', @employer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<% end %>

<%= link_to 'Back', employers_path, {class: "btn btn-default"} %>