config/routes.rb
CareerCenterApp::Application.routes.draw do
  resources :users

  resources :messages

  get "conferences/select_con" => "conferences#select_con"
  get "conferences/set_session" => "conferences#set_session"
  resources :conferences

  resources :tables

  get'employers/conf/' => "employers#index"
  get  "employers/favorites" => "employers#index", :favorites => true
  get  "employers/:id/favorite" => "employers#favorite", :as => "favorite"
  get  "employers/:id/defavorite" => "employers#defavorite", :as => "defavorite"
  get  "employers/import_form" => "employers#import_form"
  post "employers/import_from_csv" => "employers#import_from_csv"
  get  "employers/maps/:conferences" => "employers#maps"
  get  "employers/landing" => "employers#landing", :as => "landing"
  get  "employers/about_us" => "employers#about_us", :as => "about_us"

  get  "employers/map" => "employers#map"
  post "employers/map_upload" => "employers#map_upload"

  get  "employers/directions" => "employers#directions"

  resources :employers

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resource :sessions, only: [:new, :create, :destroy] , :controller => 'sessions'

   root 'employers#landing'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CareerCenterApp</title>
  <%= javascript_include_tag 'jquery', 'application' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag  "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<!-- Example Navbar-->

<nav class="navbar navbar-default" role="navigation">
  <script type="text/javascript">
    $( function(){
      $('.dropdown-toggle').dropdown()
    })
  </script>
  <div class="container">
    <div class="navbar-header" style="margin-bottom: 0px">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="margin-bottom: 0px"><img class="brand" src="https://www.parkersearch.com/dashboard/uploads/photos/usc_long1351087132.jpg" align="left" width="120" height="30"></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Employers <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="/employers">All Employers</a></li>
            <li><a href="/employers/favorites">Favorite Employers</a></li>
            <% if admin? %>
            <li class="divider"></li>
            <li><a href="/employers/new">New Employer</a></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to "Map", employers_map_path %> </li>
        <li><a href="http://sc.edu/career/">Career Center</a></li>
        <li><a href="/messages">Messages</a></li>
        <li><%= link_to "Conference", conferences_select_con_path %></li>
        <li><%= link_to "Directions", "/employers/directions"%></li>
        <% if current_con %>
          <li><%= link_to  "Fair:"+ current_con.name, conferences_select_con_path %></li>
        <% else %>
          <li><%= link_to "Job Fairs", conferences_select_con_path %></li>
        <% end %>
        <% if admin? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Admin Tools<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/users">Users</a></li>
              <li><a href="/conferences">Fairs</a></li>
              <li><a href="/conferences/new">New Fair</a></li>
              <li><a href="/messages/new">New Message</a></li>
            <!--  <li><a href="/tables/new">New Table</a></li>
              <li><a href="/tables">Table List</a></li> -->
             
              <li><%= link_to "Import from CSV", employers_import_form_path %></li>
            </ul>
        </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-right">
          <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/users/<%= current_user.id %>">View Profile</a></li>
              <li><a href="/employers/favorites">Favorite Employers</a></li>
              <li class="divider"></li>
              <li><a href="/logout">Logout</a></li>
            </ul>
          </li>
          <% else %>
            <a href="/login">Login</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div><!-- /.navbar-collapse -->
</nav>

</head>
<body>
	<div class="container">
    <center>
      <% flash.each do |name, msg| %>
        <% if name == :error %>
          <div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button><%= msg %></div> 
        <% elsif name == :success %>
          <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button><%= msg %></div> 
        <% elsif name == :notice %>
          <div class="alert alert-info"><button type="button" class="close" data-dismiss="alert">&times;</button><%= msg %></div> 
        <% end %>
      <% end %>
    </center>
		<%= yield %>
	</div>
</body>
<footer>
&copy; 2014 | Career Center Companion | <%= link_to "About Us", about_us_path %>
</footer>
</html>